name: Push_master

on:
  push:
    branches: [release/*]
  pull_request:
    branches: [release/*]

jobs:
  job1:
    name: Imprimir
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: printing
        run: echo All good
  merge-branch:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: "main"
          commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"
